
package proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReleveService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReleveService {


    /**
     * 
     * @return
     *     returns proxy.Releve
     */
    @WebMethod
    @WebResult(name = "Releve", targetNamespace = "")
    @RequestWrapper(localName = "consulterReleve", targetNamespace = "http://ws/", className = "proxy.ConsulterReleve")
    @ResponseWrapper(localName = "consulterReleveResponse", targetNamespace = "http://ws/", className = "proxy.ConsulterReleveResponse")
    @Action(input = "http://ws/ReleveService/consulterReleveRequest", output = "http://ws/ReleveService/consulterReleveResponse")
    public Releve consulterReleve();

}
